### ISSUE TITLE
Error.prototype.stack's is a data descriptor in Node 8.

### ISSUE THREAD

**Issue by andrewaustin** [mdlavin/nested-error-stacks#15]
Node 6.11.5 (v8: 5.1.281.108)
-------------
```
Object.getOwnPropertyDescriptor(new Error(), 'stack');
{ get: [Function: get stack],
  set: [Function: set stack],
  enumerable: false,
  configurable: true }
```

Node 8.9 (v8: 6.1.534.46)
---------
```
Object.getOwnPropertyDescriptor(new Error(), 'stack');
{ value: 'Error\n    at repl:1:33\n    at ContextifyScript.Script.runInThisContext (vm.js:50:33)\n    at REPLServer.defaultEval (repl.js:240:29)\n    at bound (domain.js:301:14)\n    at REPLServer.runBound [as eval] (domain.js:314:12)\n    at REPLServer.onLine (repl.js:441:10)\n    at emitOne (events.js:121:20)\n    at REPLServer.emit (events.js:211:7)\n    at REPLServer.Interface._onLine (readline.js:282:10)\n    at REPLServer.Interface._line (readline.js:631:8)',
  writable: true,
  enumerable: false,
  configurable: true }
```

This causes:
```
TypeError: Cannot read property 'call' of undefined
    at NestedError.get (node_modules/nested-error-stacks/index.js:22:52) 
```

This is due to the fact that Error.prototype.stack's descriptor changed from an accessor descriptor to a data descriptor (although I couldn't find the corresponding v8 change, I doubt it was by accident).

I plan on writing a fix, but didn't know if you had a preference on how I should fix this issue. By chance, are you up for a sem-ver major change that isn't backwards compatible? :)

**Comment by mdlavin** [comment]
If you have a fix in mind, go ahead and put a PR up. I haven't looked at it
yet.

**Comment by andrewaustin** [comment]
Actually, you had already fixed this issue but for some reason I was still looking at 1.x.
