### ISSUE TITLE
Deprecate in favor of VError

### ISSUE THREAD

**Issue by ncjones** [mdlavin/nested-error-stacks#16]
This module came up as the first search result when I searched for "nodejs nested exceptions" but after digging deeper and reading through Joyen't excellent [Node Error Handling][1] article it's clear that the [Joyent VError][2] library is the way to go with error handling in NodeJS today. I suggest you do the community a favor by updating your Readme to point users in this direction.

[1]: https://www.joyent.com/node-js/production/design/errors
[2]: https://github.com/joyent/node-verror

**Comment by mdlavin** [comment]
VError looks very good, and I might play with it myself. I'll let other decide the best library to use
