### ISSUE TITLE
Optional Message Param in Constructor

### ISSUE THREAD

**Issue by amir-zad-1** [mdlavin/nested-error-stacks#20]
Is it possible to make the message param in constructor optional?

var newErr = new NestedError("", err); => var newErr = new NestedError(err);

**Comment by mdlavin** [comment]
Your example code seems reasonable to me. I'm surprised that it would fail. Do you want to submit a PR with a fix that works for you?

**Comment by hypBox** [comment]
Thanks for the reply. I have the fix and also added a test case for it.
I will submit the PR if I have access.

**Comment by amir-zad-1** [comment]
Thank you for merging the PR. When are you going to release a new version on NPM?

**Comment by mdlavin** [comment]
I just published v2.1.0 to NPM with your changes. Thanks for contributing!
