### ISSUE TITLE
Error.captureStackTrace in browser

### ISSUE THREAD

**Issue by benallfree** [mdlavin/nested-error-stacks#9]
Hello, I think `nested-error-stacks` may not be compatible with browserify due to captureStackTrace not being defined.

I thought this would do it, but nope.

```
  if (!window.Error.captureStackTrace) {
    window.Error.captureStackTrace = function(errorObject, localContextFunction) {
      return console.log("Stack trace not supported in browser.");
    };
  }
```

**Comment by bendrucker** [comment]
See #6 as mentioned in the other thread. I don't have a vested interest in getting full parity there but someone else can totally pick up where I left off.

**Comment by StarpTech** [comment]
Hi, I would like to use the lib only on server side. Is there any plans to support browser and server? When not I would like to create a PR to remove the unnecessary https://github.com/isaacs/inherits module which can be replaced by simple `util.inherits` or class construct.

@mdlavin

**Comment by mdlavin** [comment]
I love the idea of removing the extra dependency. I'd be happy to merge a
PR that does that

**Comment by mdlavin** [comment]
Closing due to lack of browser support
